### ISSUE TITLE
Using AMD makes solution go to NaN when solution is zero (or laminar?)

### ISSUE THREAD

**Issue by SandreOuza** [glwagner/dedaLES#14]
AMD closure currently returning NaN results

**Comment by glwagner** [comment]
Can you provide a code snippet that reproduces this result?

**Comment by glwagner** [comment]
Working on this issue on the branch [AMDNaNs](https://github.com/glwagner/dedaLES/tree/AMDNaNs).

[This file](https://github.com/glwagner/dedaLES/blob/AMDNaNs/sandbox/amderror.py) reproduces the error when the parameters `a=0`. The error disappears when `a=10`.

The error returns even when `a=10` when `b` is not set initially.

**Comment by glwagner** [comment]
@SandreOuza and I have discussed how this problem is associated with the denominators of the [subgrid viscosity expression](https://github.com/glwagner/dedaLES/blob/d0bd9c67552bab0573594d6e179e9329b112d3d2/dedaLES/closures.py#L255) and [subgrid diffusivity expression](https://github.com/glwagner/dedaLES/blob/d0bd9c67552bab0573594d6e179e9329b112d3d2/dedaLES/closures.py#L282) going to zero.

@kburns any ideas how to solve this problem? I'm not sure how to implement any of the solutions I can think of (mainly involving `if` statements to catch the case that the denominator is 0) in `dedalus`.

@SandreOuza has suggested either setting a maximum value for the viscosities and diffusivities, or adding some small constant to the denominators of the viscosity and diffusivity. I dislike the idea of hard coding something with units, like a constant shift of `tr_uij`. Possibly, such a fudge factor can be a parameter that is initialized when the closure is initialized, with some sensible default. I'm just not exactly sure how we'd choose that sensible default. I don't know how to programmatically select a constant that is "small relative to `tr_uij` most of the time except when `tr_uij=0`".

Ideas?

**Comment by kburns** [comment]
It looks like for the sub grid shear viscosity and sub grid diffusivity, the resulting stress/flux should be zero when the denominators go to zero, so maybe the right way is to just short-circuit the computation of these terms and set them to zero at those points.  At first glance, though, it's not clear that the buoyancy-induced sub grid stress also goes to zero when the strain rate goes to zero, so there may be some trouble there...

**Comment by glwagner** [comment]
@kburns I think short-circuiting makes most sense. How'd you implement that in `dedalus`?

I think the buoyancy-induced term might sort out too... naively, the buoyancy-induced subgrid stress is only zero for arbitrary buoyancy fields when `wx=wy=wz=0`. If `u=v=0`, then we also have `tr_uij=0`.

**Comment by kburns** [comment]
Just to document our discussion on this... one thought is that we might want to just leave this be, since it may only come up for initial conditions, and any fix based on short-circuiting would require work to check for zeros at every tilmestep.  So maybe the best solution is to always start from slightly noisy initial conditions?

**Comment by glwagner** [comment]
Agreed.
